# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# 收集 bilibili_api 的数据文件和子模块
bilibili_datas = collect_data_files("bilibili_api")
bilibili_hidden = collect_submodules("bilibili_api")

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('bili_stat', 'bili_stat'),
        *bilibili_datas,
    ],
    hiddenimports=[
        # bilibili_api 及其子模块
        'bilibili_api',
        *bilibili_hidden,
        # bilibili_api 的核心依赖
        'bilibili_api.user',
        'bilibili_api.video',
        'bilibili_api.sync',
        'bilibili_api.Credential',
        'bilibili_api.request_settings',
        'bilibili_api.exceptions',
        'bilibili_api.clients',
        'bilibili_api.data',
        'bilibili_api.tools',
        'bilibili_api.utils',
        # bilibili_api 的第三方依赖
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.background',
        'apscheduler.triggers',
        'apscheduler.triggers.interval',
        'bs4',
        'bs4.builder',
        'bs4.builder._htmlparser',
        'bs4.builder._lxml',
        'brotli',
        'colorama',
        'lxml',
        'lxml.etree',
        'lxml.html',
        'PIL',
        'PIL.Image',
        'Cryptodome',
        'Cryptodome.Cipher',
        'Cryptodome.Cipher.AES',
        'Cryptodome.Hash',
        'Cryptodome.Hash.SHA256',
        'Cryptodome.Protocol',
        'Cryptodome.Protocol.KDF',
        'Cryptodome.Random',
        'jwt',
        'yaml',
        'pyyaml',
        'qrcode',
        'qrcode_terminal',
        'yarl',
        'multidict',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpx._transports.wsgi',
        'httpx._transports.asgi',
        'httpcore',
        'httpcore._backends',
        'httpcore._backends.sync',
        'httpcore._backends.auto',
        'httpcore._backends.trio',
        'httpcore._backends.asyncio',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'anyio._backends._trio',
        'sniffio',
        'idna',
        'certifi',
        'h11',
        'h2',
        'hpack',
        'hyperframe',
        # openpyxl 及其依赖
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.cell._writer',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'et_xmlfile',
        # PyQt5 完整模块
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtNetwork',
        'PyQt5.QtSvg',
        'PyQt5.QtXml',
        'PyQt5.sip',
        'PyQt5.Qt',
        # 其他可能需要的模块
        'json',
        'copy',
        're',
        'random',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6', 'PySide2', 'tkinter', 'matplotlib', 'numpy',
        'scipy', 'pandas', 'notebook', 'IPython', 'jupyter',
        'zmq', 'nacl', 'gi', 'clr', 'clr_loader',
        'test', 'tests', '_tests',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='B站UP主7天播放量统计',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='bili_stat\\resources\\图标.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='B站UP主7天播放量统计',
)
